### ISSUE TITLE
Add image upload to User Profile form

### ISSUE THREAD

**Issue by ctrance** [universityofcalifornia/NeXt#278]
Currently the user's image is grabbed from gravatar.com, users cannot replace that image when they edit their profile. Please add image upload to the form.

**Comment by shaun965** [comment]
@laurencullen can you help me get an image of the wave in the dimension 80x80 and in the dimension 40x40.

**Comment by laurencullen** [comment]
@shaun965 here are the icons in 80x80 and 40x40. I included both png and jpg - the png file has a transparent background and the jpg has a white background (I would recommend png unless you need  a background color).

Please let me know if you need anything else.
![waveicon40x40](https://cloud.githubusercontent.com/assets/13141571/12456735/01aad478-bf56-11e5-94ea-5d20f4506872.jpg)
![waveicon80x80](https://cloud.githubusercontent.com/assets/13141571/12456737/01ac616c-bf56-11e5-9153-538d8a2dfd65.jpg)
![waveicon40x40](https://cloud.githubusercontent.com/assets/13141571/12456738/01af4b02-bf56-11e5-828e-dcc5e142e9f8.png)
![waveicon80x80](https://cloud.githubusercontent.com/assets/13141571/12456736/01ac2bc0-bf56-11e5-90a6-091431d3eaf1.png)

**Comment by joshuaselsky** [comment]
Please fix the following issues:

* the current user's profile photo shows up for every user 
* fix the margins or padding around the profile photo in the people list

**Comment by ctrance** [comment]
@shaun965 and @joshuaselsky - the only issue to fix is "clean up the row layout to make the profile photos fill the height and still be square". I got the bug on smaller screen mobile view and on MacBook Pro

**Comment by joshuaselsky** [comment]
@ctrance It seems like this is fixed. Can you retest?

**Comment by ctrance** [comment]
@joshuaselsky @shaun965 - The mobile view is still not fixed, please see screenshot below:

Nexus 9 tablet view
![screenshot_20160201-112558](https://cloud.githubusercontent.com/assets/1034174/12963748/3a0f4176-d001-11e5-97d5-f060f8bbd392.png)

**Comment by shaun965** [comment]
As discussed in the meeting, will center the image for tablet view

**Comment by joshuaselsky** [comment]
@shaun965 in your latest PR you set the image height to 100% which causes the UI to awkward. Can you please vertically center the image?

**Comment by ctrance** [comment]
@shaun965 @joshuaselsky - The image didn't center vertically on iPad (ios 9.2.1), please see below. On iPhone, and Samsung/Nexus tablet the image is centered vertically though.

![img_0367 1](https://cloud.githubusercontent.com/assets/1034174/13403683/0daa51c4-decb-11e5-8587-bef4d9544dc3.PNG)

**Comment by joshuaselsky** [comment]
The iPad screenshot looks pretty good though! I think we should just go with it.

**Comment by ctrance** [comment]
@joshuaselsky - I'll close this then :)
